#!/usr/bin/env sh
echo "::warning ::Variable GITHUB REF - $GITHUB_REF"
echo "::warning ::Variable MERGE_TARGET - $MERGE_TARGET"


#Use MERGE_TARGET if avaialble, otherwise use GITHUB_REF
REF="${MERGE_TARGET:=$GITHUB_REF}"
echo "::warning ::Variable REF - $REF"

case "$REF" in
  'main' | 'refs/heads/main')
    BQ_PROJECT=$BQ_PROJECT
    BQ_DATASET=$BQ_DATASET
    BQ_DATASET_PD=$BQ_DATASET_PD
    BQ_KEYFILE_JSON=$BQ_KEYFILE_JSON
    BQ_LOCATION=$BQ_LOCATION
    BQ_PRIVATE_KEY=$BQ_PRIVATE_KEY
    BQ_PRIVATE_KEY_ID=$BQ_PRIVATE_KEY_ID
    BQ_CLIENT_EMAIL=$BQ_CLIENT_EMAIL
    BQ_CLIENT_ID=$BQ_CLIENT_ID
    BQ_AUTH_URI=$BQ_AUTH_URI
    BQ_TOKEN_URI=$BQ_TOKEN_URI
    BQ_AUTH_PROVIDER_X509_CERT_URL=$BQ_AUTH_PROVIDER_X509_CERT_URL
    BQ_CLIENT_X509_CERT_URI=$BQ_CLIENT_X509_CERT_URI
    ;;
esac


echo "BQ_PROJECT=$BQ_PROJECT
BQ_DATASET=$BQ_DATASET
BQ_DATASET_PD=$BQ_DATASET_PD
BQ_KEYFILE_JSON=$BQ_KEYFILE_JSON
BQ_LOCATION=$BQ_LOCATION
BQ_PRIVATE_KEY=$BQ_PRIVATE_KEY
BQ_PRIVATE_KEY_ID=$BQ_PRIVATE_KEY_ID
BQ_CLIENT_EMAIL=$BQ_CLIENT_EMAIL
BQ_CLIENT_ID=$BQ_CLIENT_ID
BQ_AUTH_URI=$BQ_AUTH_URI
BQ_TOKEN_URI=$BQ_TOKEN_URI
BQ_AUTH_PROVIDER_X509_CERT_URL=$BQ_AUTH_PROVIDER_X509_CERT_URL
BQ_CLIENT_X509_CERT_URI=$BQ_CLIENT_X509_CERT_URI" >> $GITHUB_OUTPUT