name: Deploy DBT to BigQuery

on:
  workflow_call:
    secrets:
      BQ_KEYFILE_JSON:
        required: true
      BQ_PROJECT_DEV:
        required: true
      BQ_DATASET_DEV:
        required: true
      BQ_DATASET_PD:
        required: true
      BQ_LOCATION:
        required: true
      GAR_LOCATION:
        required: true
      GAR_IMAGE_NAME:
        required: true

env:
  BQ_PROJECT_DEV: ${{ secrets.BQ_PROJECT_DEV }}
  BQ_DATASET_DEV: ${{ secrets.BQ_DATASET_DEV }}
  BQ_DATASET_PD: ${{ secrets.BQ_DATASET_PD }}
  KEYFILE_CONTENTS: ${{ secrets.BQ_KEYFILE_JSON }}
  BQ_KEYFILE: /tmp/google/google-service-account.json
  BQ_LOCATION: ${{ secrets.BQ_LOCATION }}
  GAR_LOCATION: ${{ secrets.GAR_LOCATION }}
  GAR_IMAGE_NAME: ${{ secrets.GAR_IMAGE_NAME }}

jobs:
  validate_deploy:
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install required packages
        run: |
          python -m pip install --upgrade pip

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1.1.1
        with:
          credentials_json: ${{ secrets.BQ_KEYFILE_JSON }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.BQ_PROJECT_DEV }}

      - name: Checkout dbt-common repository
        uses: actions/checkout@v3
        with:
          repository: endrit-berisha/dbt-common
          path: dbt-common

      - name: Prep Google Keyfile
        run: | 
          mkdir -p "$(dirname $BQ_KEYFILE)" 
          echo "$KEYFILE_CONTENTS" > $BQ_KEYFILE

      - name: Validate PD BQ-DBT
        id: validate_pre_deployment
        if: github.event_name == 'pull_request'
        run: |
          echo "DBT changes detected. Proceeding with pre-deployment."
          pip install -r dbt-common/requirements.txt
          python dbt-common/pd_db_manager.py \
              --project_id=${{ secrets.BQ_PROJECT_DEV }} \
              --dataset_id='${{ secrets.BQ_DATASET_PD }}' \
              --credentials_json='${{ secrets.BQ_KEYFILE_JSON }}' \
              --dbt_path='./dbt' \
              --dbt_target="pd"

      - name: Deploy BQ-DBT
        id: deployment
        if: github.event_name != 'pull_request'
        run: |
          echo "DBT changes detected. Proceeding with deployment."
          pip install -r dbt-common/requirements.txt
          python dbt-common/pd_db_manager.py \
              --project_id='${{ secrets.BQ_PROJECT_DEV }}' \
              --dataset_id='${{ secrets.BQ_DATASET_DEV }}' \
              --credentials_json='${{ secrets.BQ_KEYFILE_JSON }}' \
              --dbt_path='./dbt' \
              --dbt_target='dev'

      - name: Delete PD BQ Database
        if: always()
        run: |
          pip install -r dbt-common/requirements.txt
          python dbt-common/pd_db_manager.py \
            --project_id=${{ secrets.BQ_PROJECT_DEV }} \
            --dataset_id='${{ secrets.BQ_DATASET_PD }}' \
            --credentials_json='${{ secrets.BQ_KEYFILE_JSON }}' \
            --dbt_path=./dbt \
            --dbt_target="pd" \
            --cleanup

      - name: "Set branch name"
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |
          gcloud auth configure-docker ${{ secrets.BQ_LOCATION }}-docker.pkg.dev --quiet
      
      - name: Docker Build and Push
        if: github.event_name != 'pull_request'
        working-directory: ./dbt
        run: |
          docker build . --tag $GAR_IMAGE_NAME:$BRANCH_NAME
          docker tag $GAR_IMAGE_NAME:$BRANCH_NAME $GAR_LOCATION/$GAR_IMAGE_NAME:$BRANCH_NAME
          docker push $GAR_LOCATION/$GAR_IMAGE_NAME:$BRANCH_NAME
